export const studioConfig = {
  studioName: 'AUREN Studio',
  ownerName: 'Stanislav Hrebeniuk',
  email: 'gengrebenuck11@gmail.com',
  phone: '+491631896503',
  city: 'Kassel',
  country: 'Deutschland',
  telegramUsername: '@auren_web',
  telegramUrl: 'https://t.me/auren_web',
  websiteUrl: '',
  linkedinUrl: '',
  instagramUrl: '',
  contactRecipient: '',
  legalName: '',
  legalAddress: '',
  taxInformation: '',
  canonicalUrl: '',
};

export const projects = [
  {
    id: 'klaro',
    name: 'Klaro Reinigung',
    categoryKey: 'projects.klaroCategory',
    statusKey: 'projects.concept',
    descriptionKey: 'projects.klaroDescription',
    description: 'Modern demo website created to showcase a premium cleaning company website concept.',
    demoLabel: 'Demo Project',
    demoDisclaimer: 'Portfolio demonstration — not a real client website.',
    tasks: ['Webdesign', 'Entwicklung', 'Responsive'],
    href: 'https://cleaner-gules.vercel.app',
  },
  {
    id: 'flowers',
    name: 'With Love Flowers',
    categoryKey: 'projects.flowersCategory',
    statusKey: 'projects.flowersConcept',
    descriptionKey: 'projects.flowersDescription',
    description: 'A warm, editorial website for a personal florist with bouquets, flower subscriptions and direct enquiries.',
    demoLabel: 'Live website',
    demoDisclaimer: 'Independent portfolio project — built for a personal florist.',
    tasks: ['Webdesign', 'Entwicklung', 'Mobile first'],
    href: 'https://flowers-alpha-one.vercel.app',
  },
];
