export const translations = {
  de: {
    navigation: { projects: 'Projekte', services: 'Leistungen', process: 'Ablauf', studio: 'Studio', contact: 'Kontakt', cta: 'Projekt anfragen', menu: 'Menü öffnen', close: 'Menü schließen' },
    hero: { eyebrow: 'DIGITALSTUDIO · DEUTSCHLAND', title: 'Websites für lokale Unternehmen mit klarer Haltung.', text: 'Wir gestalten und entwickeln individuelle Websites für Dienstleister und lokale Unternehmen – durchdacht, schnell und auf echte Anfragen ausgerichtet.', primary: 'Projekt besprechen', secondary: 'Arbeiten ansehen', trust: 'Webdesign · Entwicklung · Responsive Umsetzung', browserLabel: 'Konzeptansicht', cardLabel: 'Konzept · Design · Entwicklung', preview: 'Sauber. Klar. Vor Ort.', scroll: 'Scrollen', localLabel: 'Für lokale Unternehmen' },
    projects: { eyebrow: 'AUSGEWÄHLTE ARBEITEN', title: 'Ausgewählte Arbeiten', intro: 'Eine Auswahl an Konzepten und Websites für lokale Unternehmen.', klaroCategory: 'Website-Konzept für ein Reinigungsunternehmen', concept: 'Eigenständiges Demoprojekt', klaroDescription: 'Ein moderner, klar strukturierter Webauftritt mit Leistungsübersicht, Vertrauenselementen, responsiver Umsetzung und direkter Anfragefunktion.', flowersCategory: 'Webauftritt für eine persönliche Floristin', flowersConcept: 'Live-Website', flowersDescription: 'Eine warme, redaktionelle Website für individuelle Sträuße, Blumen-Abos und persönliche Anfragen über WhatsApp.', view: 'Projekt ansehen', tasks: 'Umgesetzt', next: 'Nächstes Projekt', nextText: 'Weitere Websites und Konzepte für lokale Unternehmen sind bereits in Arbeit.' },
    services: { eyebrow: 'LEISTUNGEN', title: 'Was wir entwickeln', intro: 'Keine unnötig komplizierten Lösungen. Nur das, was Ihr Unternehmen wirklich braucht.', items: [{ title: 'Unternehmenswebsites', text: 'Moderne Websites für lokale Unternehmen, die Leistungen verständlich erklären und Vertrauen schaffen.' }, { title: 'Landingpages', text: 'Fokussierte Seiten für einzelne Angebote, Kampagnen oder die gezielte Gewinnung neuer Anfragen.' }, { title: 'Webdesign', text: 'Individuelle Gestaltung mit klarer visueller Hierarchie, responsivem Aufbau und passender Markenwirkung.' }, { title: 'Entwicklung', text: 'Saubere, schnelle und wartbare technische Umsetzung für Desktop, Tablet und Smartphone.' }, { title: 'Redesign', text: 'Überarbeitung veralteter Websites, ohne den bestehenden Charakter des Unternehmens zu verlieren.' }, { title: 'Kontakt- und Anfrageformulare', text: 'Direkte und verständliche Kontaktmöglichkeiten, damit Interessenten nicht auf dem Weg zur Anfrage verloren gehen.' }] },
    advantages: { eyebrow: 'UNSER ANSATZ', title: 'Klarer Prozess. Direkte Zusammenarbeit.', text: 'Jedes Projekt wird Schritt für Schritt entwickelt. Sie wissen jederzeit, was gerade entsteht und welche Entscheidungen als Nächstes anstehen.', items: [{ title: 'Direkter Kontakt', text: 'Sie sprechen direkt mit der Person, die Ihre Website gestaltet und entwickelt.' }, { title: 'Individuelle Umsetzung', text: 'Kein fertiges Template, das nur mit einem neuen Logo versehen wird.' }, { title: 'Mobile zuerst mitgedacht', text: 'Die Website wird nicht nachträglich verkleinert, sondern von Anfang an für alle Geräte geplant.' }, { title: 'Verständliche Kommunikation', text: 'Klare Schritte, nachvollziehbare Entscheidungen und keine unnötige Fachsprache.' }, { title: 'Saubere Übergabe', text: 'Die fertige Website wird strukturiert übergeben und kann später erweitert werden.' }] },
    process: { eyebrow: 'ABLAUF', title: 'So entsteht Ihre Website', steps: [{ n: '01', title: 'Kennenlernen', text: 'Wir klären Ihr Angebot, Ihre Zielgruppe und das wichtigste Ziel der Website.' }, { n: '02', title: 'Konzept', text: 'Struktur, Inhalte und visuelle Richtung werden festgelegt, bevor die technische Umsetzung beginnt.' }, { n: '03', title: 'Design & Entwicklung', text: 'Die Website wird gestaltet, responsiv umgesetzt und Schritt für Schritt abgestimmt.' }, { n: '04', title: 'Prüfung & Veröffentlichung', text: 'Alle wichtigen Ansichten und Funktionen werden überprüft. Danach wird die Website veröffentlicht.' }, { n: '05', title: 'Übergabe', text: 'Sie erhalten eine verständliche Übergabe und alle vereinbarten Zugänge und Dateien.' }] },
    about: { eyebrow: 'STUDIO', title: 'Kleine Struktur. Klare Verantwortung.', text: 'AUREN ist ein unabhängiges Webstudio mit Fokus auf moderne Websites für lokale Unternehmen und Dienstleister in Deutschland.', detail: 'Projekte werden direkt, transparent und ohne unnötige Zwischenebenen umgesetzt.', extra: 'Der Schwerpunkt liegt auf klarer Gestaltung, responsiver Entwicklung und einer Website, die für Besucher verständlich bleibt.', city: 'Deutschland' },
    faq: { eyebrow: 'FAQ', title: 'Häufige Fragen', items: [{ q: 'Wie lange dauert die Erstellung einer Website?', a: 'Der Zeitrahmen hängt vom Umfang und von der Verfügbarkeit der Inhalte ab. Eine kompakte Unternehmenswebsite kann in vielen Fällen innerhalb weniger Wochen umgesetzt werden.' }, { q: 'Was kostet eine Website?', a: 'Der Preis richtet sich nach Umfang, Funktionen und benötigten Inhalten. Nach einem kurzen Erstgespräch erhalten Sie ein nachvollziehbares Angebot.' }, { q: 'Können bestehende Websites überarbeitet werden?', a: 'Ja. Bestehende Websites können visuell, strukturell und technisch überarbeitet werden, sofern die vorhandene Grundlage dafür geeignet ist.' }, { q: 'Unterstützen Sie bei Texten und Bildern?', a: 'Vorhandene Inhalte können gemeinsam strukturiert und überarbeitet werden. Der konkrete Umfang wird vor Projektbeginn vereinbart.' }, { q: 'Ist die Website auf Smartphones optimiert?', a: 'Ja. Jede Website wird für Desktop, Tablet und Smartphone umgesetzt und auf wichtigen Bildschirmgrößen geprüft.' }, { q: 'Kann die Website später erweitert werden?', a: 'Die technische Struktur soll so angelegt werden, dass neue Seiten, Projekte oder Funktionen später ergänzt werden können.' }, { q: 'Wie läuft die Bezahlung ab?', a: 'Die Zahlungsbedingungen werden vor Projektbeginn transparent im Angebot vereinbart.' }] },
    contact: { eyebrow: 'KONTAKT', title: 'Sie möchten Ihr Unternehmen moderner präsentieren?', text: 'Erzählen Sie kurz, was Sie anbieten und was Ihre neue Website erreichen soll.', cta: 'Projekt anfragen', note: 'Unverbindliche erste Anfrage', formTitle: 'Projekt starten', formText: 'Schreiben Sie kurz, worum es geht. Wir melden uns schnellstmöglich zurück.', name: 'Name', company: 'Unternehmen', email: 'E-Mail', phone: 'Telefon', type: 'Art des Projekts', website: 'Aktuelle Website', message: 'Nachricht', privacy: 'Ich habe die Datenschutzerklärung gelesen und stimme der Verarbeitung meiner Angaben zu.', send: 'Anfrage senden', sending: 'Wird gesendet…', success: 'Vielen Dank! Ihre Anfrage wurde erfolgreich gesendet.', error: 'Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es später erneut oder schreiben Sie uns direkt per E-Mail.', required: 'Bitte füllen Sie dieses Feld aus.', invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.', select: 'Bitte auswählen', options: ['Neue Unternehmenswebsite', 'Landingpage', 'Redesign einer bestehenden Website', 'Technische Umsetzung', 'Noch nicht sicher'] },
    footer: { tagline: 'Webdesign & Entwicklung für lokale Unternehmen', nav: 'Navigation', legal: 'Rechtliches', imprint: 'Impressum', privacy: 'Datenschutz', placeholder: 'Inhalte folgen nach Eintragung der realen Unternehmensdaten.', rights: 'Alle Rechte vorbehalten.' },
  },
};

translations.en = JSON.parse(JSON.stringify(translations.de));
translations.ru = JSON.parse(JSON.stringify(translations.de));
Object.assign(translations.en.navigation, { projects: 'Projects', services: 'Services', process: 'Process', studio: 'Studio', contact: 'Contact', cta: 'Start a project' });
Object.assign(translations.en.hero, { eyebrow: 'DIGITAL STUDIO · GERMANY', title: 'Websites for local businesses with a clear point of view.', text: 'We design and develop individual websites for service providers and local businesses — thoughtful, fast and focused on real enquiries.', primary: 'Discuss a project', secondary: 'View our work', trust: 'Web design · Development · Responsive builds', browserLabel: 'Concept view', cardLabel: 'Concept · Design · Development', preview: 'Clear. Calm. Local.', scroll: 'Scroll to explore', localLabel: 'For local businesses' });
Object.assign(translations.en.projects, { eyebrow: 'SELECTED WORK', title: 'Selected work', intro: 'A selection of concepts and websites for local businesses.', klaroCategory: 'Website concept for a cleaning company', concept: 'Independent demo project', klaroDescription: 'A modern, clearly structured web presence with services, trust elements, responsive delivery and a direct enquiry path.', flowersCategory: 'Website for an independent florist', flowersConcept: 'Live website', flowersDescription: 'A warm, editorial website for individual bouquets, flower subscriptions and personal enquiries via WhatsApp.', view: 'View project', tasks: 'Delivered', next: 'Next project', nextText: 'More websites and concepts for local businesses are already taking shape.' });
Object.assign(translations.en.services, { eyebrow: 'SERVICES', title: 'What we build', intro: 'No unnecessarily complex solutions. Just what your business actually needs.' });
Object.assign(translations.en.advantages, { eyebrow: 'OUR APPROACH', title: 'Clear process. Direct collaboration.', text: 'Every project is developed step by step. You always know what is taking shape and which decisions come next.' });
Object.assign(translations.en.process, { eyebrow: 'PROCESS', title: 'How your website takes shape' });
Object.assign(translations.en.about, { eyebrow: 'STUDIO', title: 'Small structure. Clear responsibility.', text: 'AUREN is an independent web studio focused on modern websites for local businesses and service providers in Germany.', detail: 'Projects are delivered directly, transparently and without unnecessary layers.', extra: 'The focus is on clear design, responsive development and a website that stays understandable to visitors.' });
Object.assign(translations.en.faq, { eyebrow: 'FAQ', title: 'Frequently asked questions' });
Object.assign(translations.en.contact, { eyebrow: 'CONTACT', title: 'Ready to present your business more clearly?', text: 'Tell us briefly what you offer and what your new website should achieve.', cta: 'Start a project', note: 'No-obligation first enquiry', formTitle: 'Start a project', formText: 'Tell us briefly what it is about. We will get back to you as soon as possible.', name: 'Name', company: 'Company', email: 'Email', phone: 'Phone', type: 'Project type', website: 'Current website', message: 'Message', privacy: 'I have read the privacy policy and agree to the processing of my information.', send: 'Send enquiry', sending: 'Sending…', success: 'Thank you! Your enquiry has been sent successfully.', error: 'We could not send your enquiry. Please try again later or email us directly.', required: 'Please complete this field.', invalidEmail: 'Please enter a valid email address.', select: 'Please select' });
Object.assign(translations.en.footer, { tagline: 'Web design & development for local businesses', nav: 'Navigation', legal: 'Legal', imprint: 'Legal notice', privacy: 'Privacy policy', placeholder: 'Content will be added once the real company details are available.', rights: 'All rights reserved.' });
Object.assign(translations.ru.navigation, { projects: 'Проекты', services: 'Услуги', process: 'Процесс', studio: 'Студия', contact: 'Контакты', cta: 'Обсудить проект' });
Object.assign(translations.ru.hero, { eyebrow: 'DIGITAL-СТУДИЯ · ГЕРМАНИЯ', title: 'Сайты для локального бизнеса с ясным характером.', text: 'Мы проектируем и разрабатываем индивидуальные сайты для локальных компаний и специалистов — продуманно, быстро и с фокусом на реальные обращения.', primary: 'Обсудить проект', secondary: 'Смотреть работы', trust: 'Веб-дизайн · Разработка · Адаптивная реализация', browserLabel: 'Концепт', cardLabel: 'Концепция · Дизайн · Разработка', preview: 'Чисто. Ясно. Локально.', scroll: 'Листать дальше', localLabel: 'Для локального бизнеса' });
Object.assign(translations.ru.projects, { eyebrow: 'ИЗБРАННЫЕ РАБОТЫ', title: 'Избранные работы', intro: 'Подборка концепций и сайтов для локального бизнеса.', klaroCategory: 'Концепт сайта для клининговой компании', concept: 'Самостоятельный демо-проект', klaroDescription: 'Современный и понятный сайт с обзором услуг, блоками доверия, адаптивной реализацией и прямым сценарием обращения.', flowersCategory: 'Сайт для частного флориста', flowersConcept: 'Опубликованный сайт', flowersDescription: 'Тёплый сайт для индивидуальных букетов, цветочной подписки и личных обращений через WhatsApp.', view: 'Смотреть проект', tasks: 'Сделано', next: 'Следующий проект', nextText: 'В работе уже есть новые сайты и концепции для локального бизнеса.' });
Object.assign(translations.ru.services, { eyebrow: 'УСЛУГИ', title: 'Что мы создаём', intro: 'Без лишней сложности. Только то, что действительно нужно вашему бизнесу.' });
Object.assign(translations.ru.advantages, { eyebrow: 'ПОДХОД', title: 'Понятный процесс. Прямое сотрудничество.', text: 'Каждый проект развивается шаг за шагом. Вы всегда знаете, что создаётся сейчас и какие решения предстоят дальше.' });
Object.assign(translations.ru.process, { eyebrow: 'ПРОЦЕСС', title: 'Так создаётся ваш сайт' });
Object.assign(translations.ru.about, { eyebrow: 'СТУДИЯ', title: 'Небольшая структура. Ясная ответственность.', text: 'AUREN — независимая веб-студия, которая создаёт современные сайты для локальных компаний и специалистов в Германии.', detail: 'Проекты реализуются напрямую, прозрачно и без лишних промежуточных уровней.', extra: 'Фокус — на ясном дизайне, адаптивной разработке и понятном для посетителей сайте.' });
Object.assign(translations.ru.faq, { eyebrow: 'FAQ', title: 'Частые вопросы' });
Object.assign(translations.ru.contact, { eyebrow: 'КОНТАКТЫ', title: 'Хотите представить свой бизнес современнее?', text: 'Коротко расскажите, чем вы занимаетесь и чего должен достичь новый сайт.', cta: 'Обсудить проект', note: 'Первая заявка без обязательств', formTitle: 'Начать проект', formText: 'Напишите, что нужно сделать. Мы свяжемся с вами как можно скорее.', name: 'Имя', company: 'Компания', email: 'E-mail', phone: 'Телефон', type: 'Тип проекта', website: 'Текущий сайт', message: 'Сообщение', privacy: 'Я прочитал(а) политику конфиденциальности и согласен(на) на обработку данных.', send: 'Отправить заявку', sending: 'Отправляем…', success: 'Спасибо! Заявка успешно отправлена.', error: 'Не удалось отправить заявку. Попробуйте позже или напишите нам напрямую.', required: 'Заполните это поле.', invalidEmail: 'Введите корректный e-mail.', select: 'Выберите вариант' });
Object.assign(translations.ru.footer, { tagline: 'Веб-дизайн и разработка для локального бизнеса', nav: 'Навигация', legal: 'Правовая информация', imprint: 'Impressum', privacy: 'Конфиденциальность', placeholder: 'Содержимое появится после добавления реальных данных компании.', rights: 'Все права защищены.' });

translations.en.services.items = [
  ['Business websites', 'Modern websites for local businesses that explain services clearly and build trust.'], ['Landing pages', 'Focused pages for individual offers, campaigns or targeted enquiries.'], ['Web design', 'Individual design with clear hierarchy, responsive structure and the right brand feel.'], ['Development', 'Clean, fast and maintainable delivery for desktop, tablet and smartphone.'], ['Redesign', 'Refreshing an outdated website without losing the character of the existing business.'], ['Contact and enquiry forms', 'Direct, understandable contact paths so interested visitors do not drop off before enquiring.'],
].map(([title, text]) => ({ title, text }));
translations.ru.services.items = [
  ['Сайты компаний', 'Современные сайты для локального бизнеса, которые понятно объясняют услуги и вызывают доверие.'], ['Лендинги', 'Фокусные страницы под отдельное предложение, кампанию или сбор обращений.'], ['Веб-дизайн', 'Индивидуальная визуальная система с ясной иерархией и адаптивной структурой.'], ['Разработка', 'Чистая, быстрая и поддерживаемая реализация для компьютеров, планшетов и смартфонов.'], ['Редизайн', 'Обновление устаревшего сайта без потери характера существующего бизнеса.'], ['Формы контакта и заявки', 'Понятный путь к обращению, чтобы потенциальные клиенты не терялись до отправки заявки.'],
].map(([title, text]) => ({ title, text }));
translations.en.advantages.items = [['Direct contact', 'You speak directly with the person designing and developing your website.'], ['Individual delivery', 'No finished template with a new logo simply placed on top.'], ['Mobile considered first', 'The website is planned for every device from the start, not shrunk afterwards.'], ['Clear communication', 'Understandable steps, decisions and no unnecessary jargon.'], ['Clean handover', 'The finished website is handed over in a structured way and can grow later.']].map(([title, text]) => ({ title, text }));
translations.ru.advantages.items = [['Прямой контакт', 'Вы общаетесь напрямую с человеком, который создаёт и разрабатывает ваш сайт.'], ['Индивидуальная реализация', 'Готовый шаблон не просто получает новый логотип поверх старой структуры.'], ['Мобильная версия с самого начала', 'Сайт изначально планируется для всех устройств, а не уменьшается постфактум.'], ['Понятная коммуникация', 'Ясные шаги, решения и никакого лишнего жаргона.'], ['Аккуратная передача', 'Готовый сайт передаётся структурированно и может развиваться дальше.']].map(([title, text]) => ({ title, text }));
translations.en.process.steps = [['01', 'Getting started', 'We clarify your offer, audience and the most important goal of the website.'], ['02', 'Concept', 'Structure, content and visual direction are set before development begins.'], ['03', 'Design & development', 'The website is designed, built responsively and aligned step by step.'], ['04', 'Review & launch', 'Key views and functions are checked before the website goes live.'], ['05', 'Handover', 'You receive a clear handover with all agreed access details and files.']].map(([n, title, text]) => ({ n, title, text }));
translations.ru.process.steps = [['01', 'Знакомство', 'Мы уточняем ваше предложение, аудиторию и главную цель сайта.'], ['02', 'Концепция', 'Структура, контент и визуальное направление определяются до разработки.'], ['03', 'Дизайн и разработка', 'Сайт создаётся, адаптируется и согласовывается шаг за шагом.'], ['04', 'Проверка и публикация', 'Мы проверяем ключевые экраны и функции перед запуском.'], ['05', 'Передача', 'Вы получаете понятную передачу проекта, доступов и согласованных файлов.']].map(([n, title, text]) => ({ n, title, text }));
translations.en.faq.items = [['How long does a website take?', 'The timeframe depends on scope and content availability. A compact business website can often be delivered within a few weeks.'], ['What does a website cost?', 'Pricing depends on scope, features and content. After a short first conversation, you receive a clear proposal.'], ['Can existing websites be redesigned?', 'Yes. Existing websites can be improved visually, structurally and technically where the foundation allows it.'], ['Do you help with copy and images?', 'Existing content can be structured and refined together. The exact scope is agreed before the project starts.'], ['Is the website optimised for smartphones?', 'Yes. Every website is built for desktop, tablet and smartphone and checked across key screen sizes.'], ['Can the website be extended later?', 'The technical structure is designed so new pages, projects or features can be added later.'], ['How does payment work?', 'Payment terms are agreed transparently in the proposal before the project starts.']].map(([q, a]) => ({ q, a }));
translations.ru.faq.items = [['Сколько длится создание сайта?', 'Срок зависит от объёма и готовности материалов. Компактный сайт компании часто можно реализовать за несколько недель.'], ['Сколько стоит сайт?', 'Цена зависит от объёма, функций и необходимых материалов. После короткого разговора вы получите понятное предложение.'], ['Можно ли обновить существующий сайт?', 'Да. Существующий сайт можно обновить визуально, структурно и технически, если его основа это позволяет.'], ['Помогаете ли вы с текстами и изображениями?', 'Готовые материалы можно вместе структурировать и доработать. Конкретный объём согласуется до начала проекта.'], ['Сайт будет адаптирован для смартфонов?', 'Да. Каждый сайт создаётся для компьютеров, планшетов и смартфонов и проверяется на ключевых размерах экранов.'], ['Можно ли расширить сайт позже?', 'Структура закладывается так, чтобы позже добавлять новые страницы, проекты или функции.'], ['Как проходит оплата?', 'Условия оплаты прозрачно фиксируются в предложении до начала проекта.']].map(([q, a]) => ({ q, a }));

translations.de.services.secondaryLabel = 'Weitere Möglichkeiten';
translations.en.services.secondaryLabel = 'Also available';
translations.ru.services.secondaryLabel = 'Дополнительные возможности';
translations.de.services.items = [translations.de.services.items[2], translations.de.services.items[3], translations.de.services.items[4], translations.de.services.items[0], translations.de.services.items[1], translations.de.services.items[5]];
translations.en.services.items = [translations.en.services.items[2], translations.en.services.items[3], translations.en.services.items[4], translations.en.services.items[0], translations.en.services.items[1], translations.en.services.items[5]];
translations.ru.services.items = [translations.ru.services.items[2], translations.ru.services.items[3], translations.ru.services.items[4], translations.ru.services.items[0], translations.ru.services.items[1], translations.ru.services.items[5]];
